#ifndef DEFINITIONS_H_SEEN
#define DEFINITIONS_H_SEEN

#define DEBOUNCE_BUTTON 50

#define PIN_BUTTON_L 12
#define PIN_BUTTON_R 16
#define PIN_LED_EYES 14
#define PIN_LED_RGB  13

#define RGB_N_LEDS 12

#endif